name: webapi
channels:
  - conda-forge
dependencies:
  - ca-certificates=2021.10.8
  - libcxx=12.0.1
  - libffi=3.4.2
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=3.0.0
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.8.12
  - python_abi=3.8=2_cp38
  - readline=8.1
  - setuptools=60.5.0
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - anyio==3.5.0
      - asgiref==3.4.1
      - click==8.0.3
      - fastapi==0.72.0
      - h11==0.12.0
      - httptools==0.3.0
      - idna==3.3
      - pydantic==1.9.0
      - pymysql==1.0.2
      - python-dotenv==0.19.2
      - pyyaml==6.0
      - sniffio==1.2.0
      - starlette==0.17.1
      - typing-extensions==4.0.1
      - uvicorn==0.17.0
      - uvloop==0.16.0
      - watchgod==0.7
      - websockets==10.1
